language: ruby
sudo: false
cache: bundler
rvm:
  - "2.2"
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem update bundler
  - rm Gemfile.lock
before_script:
  - bin/rubocop
  - bin/rubocop --auto-gen-config --exclude-limit 999 --no-offense-counts --no-auto-gen-timestamp >/dev/null || true; git --no-pager diff --exit-code
